# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "brigades", :force => true do |t|
    t.string   "name"
    t.text     "description"
    t.integer  "membership_size"
    t.string   "website_url"
    t.string   "rss_url"
    t.string   "ical_url"
    t.date     "established_on"
    t.string   "city"
    t.string   "state_region"
    t.string   "country"
    t.string   "postal_code"
    t.decimal  "lat",             :precision => 15, :scale => 10
    t.decimal  "lng",             :precision => 15, :scale => 10
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
